---
version: '3.8'

services:

  # Postgres with a subset of MusicBrainz dataset:
  db:
    image: metosin/training-musicbrainz-db:latest
    init: true
    restart: always
    ports:
      - 127.0.0.1:5432:5432


  # Run node process with code compiled by shadow-cljs for cljs repl:
  node:
    image: training:dev
    build: ./docker
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/socat-tunnel.sh
    command: ["node", "index.js"]
    restart: always
    volumes:
      - ./target/node:/app
      - ./node_modules:/app/node_modules
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db


  # Proxy for serving static content and proxy /api/ trafic to application:
  proxy:
    image: caddy:2-alpine
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./public:/public
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
